

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = "REGISTER_ERROR";
export const RESET_REGISTER_STATUS = "RESET_REGISTER_STATUS";

export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGOUT = "LOGOUT";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const NO_USER_LOGGED = "NO_USER_LOGGED";


export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_FORGOT_PASSWORD_STATUS = "RESET_FORGOT_PASSWORD_STATUS";
export const SHOW_ERROR = "SHOW_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_RESET_PASSWORD_STATUS = "RESET_RESET_PASSWORD_STATUS";


export const ERR = 'ERR';